scheme: imdb
model_name: egt_110m
distributed: false
batch_size: 12
model_height: 1
node_width: 3066
edge_width: 10
num_heads: 1
num_epochs: 10
max_lr: 0.0001
attn_dropout: 0.3
lr_warmup_steps: 1000
lr_total_steps: 3000
node_ffn_multiplier: 1.0
edge_ffn_multiplier: 1.0
dataloader_workers: 1
scale_degree: true
num_virtual_nodes: 4
svd_random_neg: true
