scheme: imdb
model_name: egt_110m
distributed: false
random_seed: null
num_epochs: 10
save_path: models/imdb/egt_110m
checkpoint_path: models/imdb/egt_110m/checkpoint
config_path: models/imdb/egt_110m/config
summary_path: models/imdb/egt_110m/summary
log_path: models/imdb/egt_110m/logs
validation_frequency: 1
batch_size: 12
optimizer: Adam
max_lr: 0.0001
clip_grad_value: null
optimizer_params: {}
dataloader_workers: 1
dataloader_mp_context: forkserver
training_type: normal
evaluation_type: prediction
predictions_path: models/imdb/egt_110m/predictions
grad_accum_steps: 1
prediction_bmult: 1
state_file: null
predict_on: &id001
- test
evaluate_on: *id001
cache_dir: cache_data
dataset_name: imdb
dataset_path: cache_data/IMDB
model_height: 1
node_width: 3066
edge_width: 10
num_heads: 1
node_dropout: 0.0
edge_dropout: 0.0
node_ffn_dropout: 0.0
edge_ffn_dropout: 0.0
attn_dropout: 0.3
attn_maskout: 0.0
activation: elu
clip_logits_value:
- -5
- 5
scale_degree: true
node_ffn_multiplier: 1.0
edge_ffn_multiplier: 1.0
allocate_max_batch: true
scale_dot_product: true
egt_simple: false
verbose_lr_log: true
lr_warmup_steps: 1000
lr_total_steps: 3000
min_lr: 1.0e-06
cosine_halfwave: false
num_virtual_nodes: 4
upto_hop: 16
svd_calculated_dim: 8
svd_output_dim: 8
svd_random_neg: true
pretrained_weights_file: null
