scheme: dblp
model_name: egt_110m
distributed: false
batch_size: 2
model_height: 8
node_width: 64
edge_width: 64
num_heads: 8
num_epochs: 50
max_lr: 0.0001
attn_dropout: 0.1
lr_warmup_steps: 1000
lr_total_steps: 100000
node_ffn_multiplier: 4.0
edge_ffn_multiplier: 2.0
upto_hop: 16
dataloader_workers: 4
scale_degree: true
num_virtual_nodes: 4
svd_random_neg: true
svd_calculated_dim: 128
svd_output_dim: 64