scheme: dblp
dataset_path: cache_data/DBLP
model_name: egt_dblp
save_path: models/dblp/egt_dblp
cache_dir: cache_data/dblp
distributed: False
batch_size: 32
num_epochs: 100
max_lr: 0.0001
min_lr: 1e-6
lr_warmup_steps: 1000
lr_total_steps: 100000
model_height: 30
node_width: 128
edge_width: 64
num_heads: 8
node_ffn_multiplier: 2
edge_ffn_multiplier: 2
num_virtual_nodes: 4
upto_hop: 16
attn_dropout: 0.1
node_dropout: 0.1
edge_dropout: 0.1
sel_svd_features: 16
svd_calculated_dim: 32
svd_output_dim: 16
svd_random_neg: True
pretrained_weights_file: null